trigger:
- '*'

pool:
  vmImage: 'ubuntu-22.04'

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '6.x'
  myString: 'This is my string'  

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: Write-Host "dotnetSdkVersion:$(dotnetSdkVersion)"
- task: UseDotNet@2
  displayName: 'Use .NET SDK $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: $(wwwrootDir)

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- template: build.yaml
  parameters:
    buildConfiguration: 'Debug'

- task: DotNetCoreCLI@2
  displayName: Create SQL Scripts
  inputs:
   command: custom
   custom: 'ef '
   arguments: migrations script --output $(Build.ArtifactStagingDirectory)\AspNetCoreGitPipelineTest.sql --project D:\a\1\s\AspNetCoreGitPipelineTest\AspNetCoreGitPipelineTest.csproj

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()